# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\nController\x12\x46\n\x10\x65xecuteOperation\x12\x13.controller.Message\x1a\x1b.controller.MessageResponse\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:controller.Message)
  })
_sym_db.RegisterMessage(Message)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:controller.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

_CONTROLLER = DESCRIPTOR.services_by_name['Controller']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=32
  _MESSAGE._serialized_end=58
  _MESSAGERESPONSE._serialized_start=60
  _MESSAGERESPONSE._serialized_end=94
  _CONTROLLER._serialized_start=96
  _CONTROLLER._serialized_end=180
# @@protoc_insertion_point(module_scope)
